export const MOCK_TUTORS = [
  {
    id: '1',
    displayName: 'Dr. Anusha Perera',
    email: 'anusha.perera@submitx.app',
    contactNumber: '+94771234567',
    subject: 'Mathematics',
    username: 'anusha_perera',
    password: 'Maths@2024!',
  },
  {
    id: '2',
    displayName: 'Mr. Kasun Silva',
    email: 'kasun.silva@submitx.app',
    contactNumber: '+94712345678',
    subject: 'Biology',
    username: 'kasun_silva',
    password: 'Biology@99!',
  },
  {
    id: '3',
    displayName: 'Ms. Tharindi Wickrama',
    email: 'tharindi.w@submitx.app',
    contactNumber: '+94723456789',
    subject: 'Chemistry',
    username: 'tharindi_w',
    password: 'Chem!234A',
  },
  {
    id: '4',
    displayName: 'Mr. Rohan Fernando',
    email: 'rohan.f@submitx.app',
    contactNumber: '+94734567890',
    subject: 'Physics',
    username: 'rohan_f',
    password: 'Physics@1A!',
  },
  {
    id: '5',
    displayName: 'Ms. Nimasha Jayawardena',
    email: 'nimasha.j@submitx.app',
    contactNumber: '+94745678901',
    subject: 'English Literature',
    username: 'nimasha_j',
    password: 'Eng!Lit9X',
  },
];

export const MOCK_STUDENTS = [
  {
    id: '1',
    student_number: 'SUBMITX-2026-000001',
    first_name: 'Amal',
    last_name: 'Perera',
    email: 'amal.perera@gmail.com',
    contact_number: '+94771234567',
    date_of_birth: '2007-03-15',
    gender: 'MALE',
    whatsapp_number: '+94771234567',
    school_name: 'Royal College, Colombo',
    grade: 'Grade 12',
    subject_stream: 'Physical Science',
    guardian_name: 'Nimal Perera',
    guardian_contact: '+94112345678',
    address: '45/B, Kandy Road, Kelaniya',
    district: 'Gampaha',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '2',
    student_number: 'SUBMITX-2026-000002',
    first_name: 'Sanduni',
    last_name: 'Wickramasinghe',
    email: 'sanduni.w@gmail.com',
    contact_number: '+94712345678',
    date_of_birth: '2008-07-22',
    gender: 'FEMALE',
    whatsapp_number: '+94712345678',
    school_name: 'Visakha Vidyalaya, Colombo',
    grade: 'Grade 11',
    subject_stream: 'Commerce',
    guardian_name: 'Priya Wickramasinghe',
    guardian_contact: '+94114567890',
    address: '12, Temple Road, Maharagama',
    district: 'Colombo',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '3',
    student_number: 'SUBMITX-2026-000003',
    first_name: 'Kasun',
    last_name: 'Jayawardena',
    email: 'kasun.j@gmail.com',
    contact_number: '+94723456789',
    date_of_birth: '2006-11-05',
    gender: 'MALE',
    whatsapp_number: '+94723456789',
    school_name: 'Nalanda College, Colombo',
    grade: 'Grade 13',
    subject_stream: 'Biological Science',
    guardian_name: 'Sunil Jayawardena',
    guardian_contact: '+94113456789',
    address: '78, Galle Road, Kalutara',
    district: 'Kalutara',
    profile_photo_url: null,
    status: 'INACTIVE',
  },
  {
    id: '4',
    student_number: 'SUBMITX-2026-000004',
    first_name: 'Dilini',
    last_name: 'Bandara',
    email: 'dilini.b@gmail.com',
    contact_number: '+94734567890',
    date_of_birth: '2007-09-18',
    gender: 'FEMALE',
    whatsapp_number: '+94734567890',
    school_name: "Girls' High School, Kandy",
    grade: 'Grade 12',
    subject_stream: 'Arts',
    guardian_name: 'Kumari Bandara',
    guardian_contact: '+94814567890',
    address: '23, Peradeniya Road, Kandy',
    district: 'Kandy',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '5',
    student_number: 'SUBMITX-2026-000005',
    first_name: 'Tharaka',
    last_name: 'Silva',
    email: 'tharaka.s@gmail.com',
    contact_number: '+94745678901',
    date_of_birth: '2005-04-30',
    gender: 'MALE',
    whatsapp_number: '+94745678901',
    school_name: 'Dharmaraja College, Kandy',
    grade: 'Grade 13',
    subject_stream: 'Technology',
    guardian_name: 'Ruwan Silva',
    guardian_contact: '+94815678901',
    address: '56, Hospital Road, Matale',
    district: 'Matale',
    profile_photo_url: null,
    status: 'GRADUATED',
  },
];

export const MOCK_ADMIN_INSTRUCTORS = [
  {
    id: '1',
    employee_id: 'INS-001',
    first_name: 'Priya',
    last_name: 'Fernando',
    email: 'priya.f@submitx.app',
    contact_number: '+94771111111',
    subject_area: 'Mathematics',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
  {
    id: '2',
    employee_id: 'INS-002',
    first_name: 'Asanka',
    last_name: 'Gunawardena',
    email: 'asanka.g@submitx.app',
    contact_number: '+94772222222',
    subject_area: 'Physics',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
  {
    id: '3',
    employee_id: 'INS-003',
    first_name: 'Nirmala',
    last_name: 'Amarasinghe',
    email: 'nirmala.a@submitx.app',
    contact_number: '+94773333333',
    subject_area: 'English Literature',
    status: 'INACTIVE',
    profile_photo_url: null,
  },
  {
    id: '4',
    employee_id: 'INS-004',
    first_name: 'Chaminda',
    last_name: 'Rathnayake',
    email: 'chaminda.r@submitx.app',
    contact_number: '+94774444444',
    subject_area: 'Chemistry',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
];

export const MOCK_TEACHER_CLASSES = [
  {
    id: '1',
    title: 'Advanced Mathematics',
    description: 'A comprehensive course covering calculus, algebra, and statistics for advanced students.',
    imageUrl: null,
    fee: 2500,
    status: 'ACTIVE',
    grade: 'Grade 12',
    subject: 'Mathematics',
  },
  {
    id: '2',
    title: 'Biology Fundamentals',
    description: 'Introduction to cell biology, genetics, and ecosystems.',
    imageUrl: null,
    fee: 2000,
    status: 'ACTIVE',
    grade: 'Grade 10',
    subject: 'Biology',
  },
  {
    id: '3',
    title: 'Chemistry Lab',
    description: 'Practical chemistry with lab sessions and theory.',
    imageUrl: null,
    fee: 3000,
    status: 'INACTIVE',
    grade: 'Grade 11',
    subject: 'Chemistry',
  },
  {
    id: '4',
    title: 'English Literature',
    description: 'Analysis of classic and contemporary literary works.',
    imageUrl: null,
    fee: 1800,
    status: 'ACTIVE',
    grade: 'Grade 9',
    subject: 'English',
  },
];

export const MOCK_INSTRUCTORS = [
  {
    id: '1',
    employee_id: 'EMP-001',
    name: 'Mr. Chamara Perera',
    status: 'ACTIVE',
  },
  {
    id: '2',
    employee_id: 'EMP-042',
    name: 'Ms. Dilini Jayawardena',
    status: 'ACTIVE',
  },
  {
    id: '3',
    employee_id: 'EMP-107',
    name: 'Mr. Saman Bandara',
    status: 'ACTIVE',
  },
];

export const MOCK_LOGGED_IN_STUDENT = {
  id: '1',
  student_number: 'SUBMITX-2026-000001',
  first_name: 'Amal',
  last_name: 'Perera',
  email: 'amal.perera@gmail.com',
  contact_number: '+94771234567',
  date_of_birth: '2007-03-15',
  gender: 'MALE',
  whatsapp_number: '+94771234567',
  school_name: 'Royal College, Colombo',
  grade: 'Grade 12',
  subject_stream: 'Physical Science',
  guardian_name: 'Nimal Perera',
  guardian_contact: '+94112345678',
  address: '45/B, Kandy Road, Kelaniya',
  district: 'Gampaha',
  profile_photo_url: null,
  status: 'ACTIVE',
};

export const MOCK_STUDENT_ENROLLED_CLASSES = [
  {
    id: 'ec-001',
    class_name: 'Grade 12 Advanced Mathematics',
    class_year: '2026',
    teacher_name: 'Dr. Anusha Perera',
    subject: 'Mathematics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'PAID',
    enrolled_at: '2026-01-15T08:00:00.000Z',
    monthly_fee: 2500,
    description: 'A comprehensive course covering calculus, algebra, and statistics for advanced students preparing for A/L examinations.',
  },
  {
    id: 'ec-002',
    class_name: 'Grade 12 Physics',
    class_year: '2026',
    teacher_name: 'Mr. Rohan Fernando',
    subject: 'Physics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'PAID',
    enrolled_at: '2026-01-20T09:00:00.000Z',
    monthly_fee: 2800,
    description: 'Advanced Physics covering mechanics, electromagnetism, waves, and modern physics with practical sessions.',
  },
  {
    id: 'ec-003',
    class_name: 'Grade 12 Combined Mathematics',
    class_year: '2026',
    teacher_name: 'Ms. Tharindi Wickrama',
    subject: 'Combined Mathematics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'PENDING',
    enrolled_at: '2026-02-01T10:00:00.000Z',
    monthly_fee: 3000,
    description: 'Pure and Applied Mathematics combined course for Physical Science stream students.',
  },
  {
    id: 'ec-004',
    class_name: 'Grade 12 Chemistry',
    class_year: '2026',
    teacher_name: 'Mr. Kasun Silva',
    subject: 'Chemistry',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'REJECTED',
    enrolled_at: '2026-02-05T11:00:00.000Z',
    monthly_fee: 2600,
    description: 'Comprehensive Chemistry course covering organic, inorganic, and physical chemistry with lab practicals.',
  },
];

export const MOCK_PAYMENTS = [
  // ── PENDING (4) ────────────────────────────────────────────────────────────
  {
    id: 'pay-001',
    student_id: '1',
    student_name: 'Amal Perera',
    student_number: 'SUBMITX-2026-000001',
    teacher_name: 'Mr. Kasun Silva',
    class_name: 'Grade 10 Biology Fundamentals',
    amount: 2000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-09T08:15:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-002',
    student_id: '2',
    student_name: 'Sanduni Wickramasinghe',
    student_number: 'SUBMITX-2026-000002',
    teacher_name: 'Ms. Nimasha Jayawardena',
    class_name: 'Grade 9 English Literature',
    amount: 1800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-09T11:30:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-003',
    student_id: '3',
    student_name: 'Kasun Jayawardena',
    student_number: 'SUBMITX-2026-000003',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-08T14:45:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-004',
    student_id: '4',
    student_name: 'Dilini Bandara',
    student_number: 'SUBMITX-2026-000004',
    teacher_name: 'Ms. Tharindi Wickrama',
    class_name: 'Grade 11 Chemistry Lab',
    amount: 3000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-08T09:00:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  // ── APPROVED (3) ───────────────────────────────────────────────────────────
  {
    id: 'pay-005',
    student_id: '5',
    student_name: 'Tharaka Silva',
    student_number: 'SUBMITX-2026-000005',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'BOC-2026-TXN-00441',
    rejection_reason: null,
    submitted_at: '2026-06-07T10:00:00.000Z',
    reviewed_at: '2026-06-07T15:30:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  {
    id: 'pay-006',
    student_id: '1',
    student_name: 'Amal Perera',
    student_number: 'SUBMITX-2026-000001',
    teacher_name: 'Ms. Nimasha Jayawardena',
    class_name: 'Grade 9 English Literature',
    amount: 1800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'HNB-2026-RTF-08812',
    rejection_reason: null,
    submitted_at: '2026-06-06T13:00:00.000Z',
    reviewed_at: '2026-06-06T16:45:00.000Z',
    reviewed_by: 'Dinesh Bandara',
  },
  {
    id: 'pay-007',
    student_id: '2',
    student_name: 'Sanduni Wickramasinghe',
    student_number: 'SUBMITX-2026-000002',
    teacher_name: 'Mr. Kasun Silva',
    class_name: 'Grade 10 Biology Fundamentals',
    amount: 2000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'COMM-2026-CRD-55019',
    rejection_reason: null,
    submitted_at: '2026-06-05T09:30:00.000Z',
    reviewed_at: '2026-06-05T11:15:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  // ── REJECTED (3) ───────────────────────────────────────────────────────────
  {
    id: 'pay-008',
    student_id: '3',
    student_name: 'Kasun Jayawardena',
    student_number: 'SUBMITX-2026-000003',
    teacher_name: 'Ms. Tharindi Wickrama',
    class_name: 'Grade 11 Chemistry Lab',
    amount: 3000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'Receipt image is blurry and unreadable. Please upload a clear photograph of the bank deposit slip.',
    submitted_at: '2026-06-07T08:00:00.000Z',
    reviewed_at: '2026-06-07T09:30:00.000Z',
    reviewed_by: 'Dinesh Bandara',
  },
  {
    id: 'pay-009',
    student_id: '4',
    student_name: 'Dilini Bandara',
    student_number: 'SUBMITX-2026-000004',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'The deposited amount (LKR 2,000) does not match the required fee (LKR 2,500). Please deposit the correct amount and resubmit.',
    submitted_at: '2026-06-06T07:45:00.000Z',
    reviewed_at: '2026-06-06T10:00:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  {
    id: 'pay-010',
    student_id: '5',
    student_name: 'Tharaka Silva',
    student_number: 'SUBMITX-2026-000005',
    teacher_name: 'Mr. Rohan Fernando',
    class_name: 'Grade 13 Physics',
    amount: 2800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'Duplicate submission — this payment has already been processed under reference BOC-2026-TXN-00441.',
    submitted_at: '2026-06-05T14:00:00.000Z',
    reviewed_at: '2026-06-05T16:30:00.000Z',
    reviewed_by: 'Sanduni Madushanka',
  },
];

export const MOCK_CASHIERS = [
  {
    id: '1',
    fullName: 'Priya Rathnayake',
    email: 'priya.r@submitx.app',
    username: 'priya_r',
    password: 'Cash!2024X',
  },
  {
    id: '2',
    fullName: 'Dinesh Bandara',
    email: 'dinesh.b@submitx.app',
    username: 'dinesh_b',
    password: 'Desk@99A!',
  },
  {
    id: '3',
    fullName: 'Sanduni Madushanka',
    email: 'sanduni.m@submitx.app',
    username: 'sanduni_m',
    password: 'Sand!Pay8Z',
  },
];
