export const MOCK_TUTORS = [
  {
    id: '1',
    displayName: 'Dr. Anusha Perera',
    email: 'anusha.perera@submitx.app',
    contactNumber: '+94771234567',
    subject: 'Mathematics',
    username: 'anusha_perera',
    password: 'Maths@2024!',
    teacher_name: 'Dr. Anusha Perera',
    subject_area: 'Mathematics',
    profile_image_url: null,
    bio: 'Advanced mathematics teacher focused on A/L problem solving and structured revision.',
    classes: [
      {
        id: 'tc-001',
        class_name: 'Grade 12 Advanced Mathematics',
        class_year: '2026',
        subject: 'Mathematics',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 2500,
        description: 'A comprehensive course covering calculus, algebra, and statistics for advanced students.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-002',
        class_name: 'Grade 13 Combined Revision',
        class_year: '2026',
        subject: 'Mathematics',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 3200,
        description: 'Intensive combined mathematics revision for Grade 13 students targeting university entrance.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-003',
        class_name: 'Grade 11 Mathematics',
        class_year: '2026',
        subject: 'Mathematics',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 2000,
        description: 'Foundation mathematics for O/L students building up to advanced topics.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: '2',
    displayName: 'Mr. Kasun Silva',
    email: 'kasun.silva@submitx.app',
    contactNumber: '+94712345678',
    subject: 'Biology',
    username: 'kasun_silva',
    password: 'Biology@99!',
    teacher_name: 'Mr. Kasun Silva',
    subject_area: 'Biology',
    profile_image_url: null,
    bio: 'Experienced biology teacher with focus on A/L Biology and life sciences.',
    classes: [
      {
        id: 'tc-004',
        class_name: 'Grade 12 Biology',
        class_year: '2026',
        subject: 'Biology',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 2200,
        description: 'A/L Biology covering cell biology, genetics, ecology, and human physiology.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-005',
        class_name: 'Grade 10 Biology Fundamentals',
        class_year: '2026',
        subject: 'Biology',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 1800,
        description: 'Introduction to cell biology, genetics, and ecosystems for O/L students.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: '3',
    displayName: 'Ms. Tharindi Wickrama',
    email: 'tharindi.w@submitx.app',
    contactNumber: '+94723456789',
    subject: 'Chemistry',
    username: 'tharindi_w',
    password: 'Chem!234A',
    teacher_name: 'Ms. Tharindi Wickrama',
    subject_area: 'Chemistry',
    profile_image_url: null,
    bio: 'Chemistry teacher covering organic, inorganic, and physical chemistry with weekly paper practice.',
    classes: [
      {
        id: 'tc-006',
        class_name: 'Grade 12 Chemistry',
        class_year: '2026',
        subject: 'Chemistry',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 2600,
        description: 'Comprehensive A/L Chemistry covering organic, inorganic, and physical chemistry.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-007',
        class_name: 'Grade 11 Chemistry Lab',
        class_year: '2026',
        subject: 'Chemistry',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 3000,
        description: 'Practical chemistry with lab sessions and theory for O/L advanced students.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-008',
        class_name: 'Grade 13 Chemistry Revision',
        class_year: '2026',
        subject: 'Chemistry',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 3500,
        description: 'Intensive A/L Chemistry revision targeting exam excellence.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: '4',
    displayName: 'Mr. Rohan Fernando',
    email: 'rohan.f@submitx.app',
    contactNumber: '+94734567890',
    subject: 'Physics',
    username: 'rohan_f',
    password: 'Physics@1A!',
    teacher_name: 'Mr. Rohan Fernando',
    subject_area: 'Physics',
    profile_image_url: null,
    bio: 'Physics classes with practical examples, model papers, and exam-focused discussion.',
    classes: [
      {
        id: 'tc-009',
        class_name: 'Grade 12 Physics',
        class_year: '2026',
        subject: 'Physics',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 2800,
        description: 'A/L Physics covering mechanics, electromagnetism, waves, and modern physics.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-010',
        class_name: 'Grade 13 Mechanics Revision',
        class_year: '2026',
        subject: 'Physics',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 3000,
        description: 'Focused revision on mechanics and electromagnetism for A/L Physics students.',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: '5',
    displayName: 'Ms. Nimasha Jayawardena',
    email: 'nimasha.j@submitx.app',
    contactNumber: '+94745678901',
    subject: 'English Literature',
    username: 'nimasha_j',
    password: 'Eng!Lit9X',
    teacher_name: 'Ms. Nimasha Jayawardena',
    subject_area: 'English Literature',
    profile_image_url: null,
    bio: 'English Literature specialist with expertise in both classic and contemporary literary texts.',
    classes: [
      {
        id: 'tc-011',
        class_name: 'Grade 12 English Literature',
        class_year: '2026',
        subject: 'English Literature',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 1800,
        description: 'Analysis of classic and contemporary literary works for A/L English Literature.',
        status: 'ACTIVE',
      },
      {
        id: 'tc-012',
        class_name: 'Grade 9 English Literature',
        class_year: '2026',
        subject: 'English Literature',
        image_url: 'https://placehold.co/400x200?text=Class+Image',
        monthly_fee: 1500,
        description: 'Foundation English Literature for O/L students exploring poetry, prose, and drama.',
        status: 'ACTIVE',
      },
    ],
  },
];

export const MOCK_STUDENTS = [
  {
    id: '1',
    student_number: 'SUBMITX-2026-000001',
    first_name: 'Amal',
    last_name: 'Perera',
    email: 'amal.perera@gmail.com',
    contact_number: '+94771234567',
    date_of_birth: '2007-03-15',
    gender: 'MALE',
    whatsapp_number: '+94771234567',
    school_name: 'Royal College, Colombo',
    grade: 'Grade 12',
    subject_stream: 'Physical Science',
    guardian_name: 'Nimal Perera',
    guardian_contact: '+94112345678',
    address: '45/B, Kandy Road, Kelaniya',
    district: 'Gampaha',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '2',
    student_number: 'SUBMITX-2026-000002',
    first_name: 'Sanduni',
    last_name: 'Wickramasinghe',
    email: 'sanduni.w@gmail.com',
    contact_number: '+94712345678',
    date_of_birth: '2008-07-22',
    gender: 'FEMALE',
    whatsapp_number: '+94712345678',
    school_name: 'Visakha Vidyalaya, Colombo',
    grade: 'Grade 11',
    subject_stream: 'Commerce',
    guardian_name: 'Priya Wickramasinghe',
    guardian_contact: '+94114567890',
    address: '12, Temple Road, Maharagama',
    district: 'Colombo',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '3',
    student_number: 'SUBMITX-2026-000003',
    first_name: 'Kasun',
    last_name: 'Jayawardena',
    email: 'kasun.j@gmail.com',
    contact_number: '+94723456789',
    date_of_birth: '2006-11-05',
    gender: 'MALE',
    whatsapp_number: '+94723456789',
    school_name: 'Nalanda College, Colombo',
    grade: 'Grade 13',
    subject_stream: 'Biological Science',
    guardian_name: 'Sunil Jayawardena',
    guardian_contact: '+94113456789',
    address: '78, Galle Road, Kalutara',
    district: 'Kalutara',
    profile_photo_url: null,
    status: 'INACTIVE',
  },
  {
    id: '4',
    student_number: 'SUBMITX-2026-000004',
    first_name: 'Dilini',
    last_name: 'Bandara',
    email: 'dilini.b@gmail.com',
    contact_number: '+94734567890',
    date_of_birth: '2007-09-18',
    gender: 'FEMALE',
    whatsapp_number: '+94734567890',
    school_name: "Girls' High School, Kandy",
    grade: 'Grade 12',
    subject_stream: 'Arts',
    guardian_name: 'Kumari Bandara',
    guardian_contact: '+94814567890',
    address: '23, Peradeniya Road, Kandy',
    district: 'Kandy',
    profile_photo_url: null,
    status: 'ACTIVE',
  },
  {
    id: '5',
    student_number: 'SUBMITX-2026-000005',
    first_name: 'Tharaka',
    last_name: 'Silva',
    email: 'tharaka.s@gmail.com',
    contact_number: '+94745678901',
    date_of_birth: '2005-04-30',
    gender: 'MALE',
    whatsapp_number: '+94745678901',
    school_name: 'Dharmaraja College, Kandy',
    grade: 'Grade 13',
    subject_stream: 'Technology',
    guardian_name: 'Ruwan Silva',
    guardian_contact: '+94815678901',
    address: '56, Hospital Road, Matale',
    district: 'Matale',
    profile_photo_url: null,
    status: 'GRADUATED',
  },
];

export const MOCK_ADMIN_INSTRUCTORS = [
  {
    id: '1',
    employee_id: 'INS-001',
    first_name: 'Priya',
    last_name: 'Fernando',
    email: 'priya.f@submitx.app',
    contact_number: '+94771111111',
    subject_area: 'Mathematics',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
  {
    id: '2',
    employee_id: 'INS-002',
    first_name: 'Asanka',
    last_name: 'Gunawardena',
    email: 'asanka.g@submitx.app',
    contact_number: '+94772222222',
    subject_area: 'Physics',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
  {
    id: '3',
    employee_id: 'INS-003',
    first_name: 'Nirmala',
    last_name: 'Amarasinghe',
    email: 'nirmala.a@submitx.app',
    contact_number: '+94773333333',
    subject_area: 'English Literature',
    status: 'INACTIVE',
    profile_photo_url: null,
  },
  {
    id: '4',
    employee_id: 'INS-004',
    first_name: 'Chaminda',
    last_name: 'Rathnayake',
    email: 'chaminda.r@submitx.app',
    contact_number: '+94774444444',
    subject_area: 'Chemistry',
    status: 'ACTIVE',
    profile_photo_url: null,
  },
];

export const MOCK_TEACHER_CLASSES = [
  {
    id: '1',
    display_name: '2026 A/L English Medium',
    subject_name: 'Combined Mathematics',
    description: 'Advanced Level Combined Mathematics conducted in English medium. Covers Pure and Applied Mathematics for the 2026 examination.',
    monthly_fee: 3500,
    status: 'ACTIVE',
    papers: [
      {
        id: 'paper-1-1',
        paper_name: 'June 2026 — Paper 01',
        month: 6,
        year: 2026,
        month_label: 'June 2026',
        number_of_questions: 10,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2026-06-01T08:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-1-2',
        paper_name: 'May 2026 — Paper 01',
        month: 5,
        year: 2026,
        month_label: 'May 2026',
        number_of_questions: 10,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2026-05-03T09:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-1-3',
        paper_name: 'April 2026 — Paper 01',
        month: 4,
        year: 2026,
        month_label: 'April 2026',
        number_of_questions: 8,
        pdf_url: null,
        uploaded_at: '2026-04-05T10:00:00.000Z',
        status: 'DRAFT',
      },
    ],
  },
  {
    id: '2',
    display_name: '2026 A/L Sinhala Medium',
    subject_name: 'Combined Mathematics',
    description: 'Advanced Level Combined Mathematics conducted in Sinhala medium for the 2026 examination.',
    monthly_fee: 3000,
    status: 'ACTIVE',
    papers: [
      {
        id: 'paper-2-1',
        paper_name: 'June 2026 — Paper 01',
        month: 6,
        year: 2026,
        month_label: 'June 2026',
        number_of_questions: 10,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2026-06-02T08:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-2-2',
        paper_name: 'May 2026 — Paper 01',
        month: 5,
        year: 2026,
        month_label: 'May 2026',
        number_of_questions: 10,
        pdf_url: null,
        uploaded_at: '2026-05-05T09:00:00.000Z',
        status: 'DRAFT',
      },
      {
        id: 'paper-2-3',
        paper_name: 'April 2026 — Paper 01',
        month: 4,
        year: 2026,
        month_label: 'April 2026',
        number_of_questions: 8,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2026-04-03T10:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-2-4',
        paper_name: 'March 2026 — Paper 01',
        month: 3,
        year: 2026,
        month_label: 'March 2026',
        number_of_questions: 10,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2026-03-04T08:30:00.000Z',
        status: 'PUBLISHED',
      },
    ],
  },
  {
    id: '3',
    display_name: '2027 A/L English Medium',
    subject_name: 'Combined Mathematics',
    description: 'Advanced Level Combined Mathematics in English medium for students sitting the 2027 examination.',
    monthly_fee: 3500,
    status: 'ACTIVE',
    papers: [
      {
        id: 'paper-3-1',
        paper_name: 'June 2026 — Paper 01',
        month: 6,
        year: 2026,
        month_label: 'June 2026',
        number_of_questions: 10,
        pdf_url: null,
        uploaded_at: '2026-06-10T11:00:00.000Z',
        status: 'DRAFT',
      },
      {
        id: 'paper-3-2',
        paper_name: 'May 2026 — Paper 01',
        month: 5,
        year: 2026,
        month_label: 'May 2026',
        number_of_questions: 10,
        pdf_url: null,
        uploaded_at: '2026-05-12T09:00:00.000Z',
        status: 'DRAFT',
      },
      {
        id: 'paper-3-3',
        paper_name: 'April 2026 — Paper 01',
        month: 4,
        year: 2026,
        month_label: 'April 2026',
        number_of_questions: 10,
        pdf_url: null,
        uploaded_at: '2026-04-10T10:00:00.000Z',
        status: 'DRAFT',
      },
    ],
  },
  {
    id: '4',
    display_name: '2025 Revision Class',
    subject_name: 'Combined Mathematics',
    description: 'Intensive revision class covering past paper discussions and exam techniques for 2025 A/L candidates.',
    monthly_fee: 2000,
    status: 'INACTIVE',
    papers: [
      {
        id: 'paper-4-1',
        paper_name: 'December 2025 — Paper 05',
        month: 12,
        year: 2025,
        month_label: 'December 2025',
        number_of_questions: 15,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2025-12-01T08:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-4-2',
        paper_name: 'November 2025 — Paper 04',
        month: 11,
        year: 2025,
        month_label: 'November 2025',
        number_of_questions: 15,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2025-11-02T08:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-4-3',
        paper_name: 'October 2025 — Paper 03',
        month: 10,
        year: 2025,
        month_label: 'October 2025',
        number_of_questions: 12,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2025-10-05T09:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-4-4',
        paper_name: 'September 2025 — Paper 02',
        month: 9,
        year: 2025,
        month_label: 'September 2025',
        number_of_questions: 10,
        pdf_url: 'https://placehold.co/pdf',
        uploaded_at: '2025-09-04T10:00:00.000Z',
        status: 'PUBLISHED',
      },
      {
        id: 'paper-4-5',
        paper_name: 'August 2025 — Paper 01',
        month: 8,
        year: 2025,
        month_label: 'August 2025',
        number_of_questions: 10,
        pdf_url: null,
        uploaded_at: '2025-08-10T08:00:00.000Z',
        status: 'DRAFT',
      },
    ],
  },
];

export const MOCK_INSTRUCTORS = [
  {
    id: '1',
    employee_id: 'EMP-001',
    name: 'Mr. Chamara Perera',
    status: 'ACTIVE',
  },
  {
    id: '2',
    employee_id: 'EMP-042',
    name: 'Ms. Dilini Jayawardena',
    status: 'ACTIVE',
  },
  {
    id: '3',
    employee_id: 'EMP-107',
    name: 'Mr. Saman Bandara',
    status: 'ACTIVE',
  },
];

export const MOCK_LOGGED_IN_INSTRUCTOR = {
  id: '1',
  employee_id: 'EMP-001',
  first_name: 'Chamara',
  last_name: 'Perera',
  email: 'chamara.perera@submitx.app',
  contact_number: '+94775550123',
  subject_area: 'Mathematics',
  status: 'ACTIVE',
  profile_photo_url: null,
  created_at: '2026-01-10T08:30:00.000Z',
};

export const MOCK_INSTRUCTOR_TEACHERS = [
  {
    id: 'teacher-001',
    teacher_name: 'Dr. Anusha Perera',
    subject_area: 'Mathematics',
    bio: 'Advanced mathematics teacher focused on A/L problem solving and structured revision.',
    classes: [
      {
        id: 'class-001',
        class_name: 'Grade 12 Advanced Mathematics',
        class_year: '2026',
        subject: 'Mathematics',
        monthly_fee: 2500,
        status: 'ACTIVE',
      },
      {
        id: 'class-002',
        class_name: 'Grade 13 Combined Revision',
        class_year: '2026',
        subject: 'Combined Mathematics',
        monthly_fee: 3200,
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'teacher-002',
    teacher_name: 'Mr. Rohan Fernando',
    subject_area: 'Physics',
    bio: 'Physics classes with practical examples, model papers, and exam-focused discussion.',
    classes: [
      {
        id: 'class-003',
        class_name: 'Grade 12 Physics',
        class_year: '2026',
        subject: 'Physics',
        monthly_fee: 2800,
        status: 'ACTIVE',
      },
      {
        id: 'class-004',
        class_name: 'Grade 13 Mechanics Revision',
        class_year: '2026',
        subject: 'Physics',
        monthly_fee: 3000,
        status: 'INACTIVE',
      },
    ],
  },
  {
    id: 'teacher-003',
    teacher_name: 'Ms. Tharindi Wickrama',
    subject_area: 'Chemistry',
    bio: 'Chemistry teacher covering organic, inorganic, and physical chemistry with weekly paper practice.',
    classes: [
      {
        id: 'class-005',
        class_name: 'Grade 12 Chemistry',
        class_year: '2026',
        subject: 'Chemistry',
        monthly_fee: 2600,
        status: 'ACTIVE',
      },
    ],
  },
];

export const MOCK_LOGGED_IN_STUDENT = {
  id: '1',
  student_number: 'SUBMITX-2026-000001',
  first_name: 'Amal',
  last_name: 'Perera',
  email: 'amal.perera@gmail.com',
  contact_number: '+94771234567',
  date_of_birth: '2007-03-15',
  gender: 'MALE',
  whatsapp_number: '+94771234567',
  school_name: 'Royal College, Colombo',
  grade: 'Grade 12',
  subject_stream: 'Physical Science',
  guardian_name: 'Nimal Perera',
  guardian_contact: '+94112345678',
  address: '45/B, Kandy Road, Kelaniya',
  district: 'Gampaha',
  profile_photo_url: null,
  status: 'ACTIVE',
};

export const MOCK_STUDENT_ENROLLED_CLASSES = [
  {
    id: 'ec-001',
    class_name: 'Grade 12 Advanced Mathematics',
    class_year: '2026',
    teacher_name: 'Dr. Anusha Perera',
    subject: 'Mathematics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'PAID',
    enrolled_at: '2026-01-15T08:00:00.000Z',
    monthly_fee: 2500,
    description: 'A comprehensive course covering calculus, algebra, and statistics for advanced students preparing for A/L examinations.',
    papers: [
      {
        id: 'paper-001-1',
        paper_name: 'Monthly Paper 01 – June 2026',
        due_date: '2026-06-20T23:59:00.000Z',
        submission_status: 'NOT_SUBMITTED',
      },
      {
        id: 'paper-001-2',
        paper_name: 'Revision Paper – Calculus',
        due_date: '2026-06-28T23:59:00.000Z',
        submission_status: 'SUBMITTED',
      },
    ],
    previous_papers: [
      {
        id: 'prev-001-1',
        paper_name: 'Monthly Paper 01 – April 2026',
        due_date: '2026-04-20T23:59:00.000Z',
        grade: '88/100',
        status: 'GRADED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: 'https://placehold.co/600x800?text=My+Submission',
        graded_pdf_url: 'https://placehold.co/600x800?text=Graded+Submission',
      },
      {
        id: 'prev-001-2',
        paper_name: 'Monthly Paper 02 – April 2026',
        due_date: '2026-04-28T23:59:00.000Z',
        grade: null,
        status: 'SUBMITTED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: 'https://placehold.co/600x800?text=My+Submission',
      },
      {
        id: 'prev-001-3',
        paper_name: 'Monthly Paper 01 – March 2026',
        due_date: '2026-03-20T23:59:00.000Z',
        grade: '74/100',
        status: 'GRADED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: 'https://placehold.co/600x800?text=My+Submission',
        graded_pdf_url: 'https://placehold.co/600x800?text=Graded+Submission',
      },
      {
        id: 'prev-001-4',
        paper_name: 'Monthly Paper 02 – March 2026',
        due_date: '2026-03-28T23:59:00.000Z',
        grade: null,
        status: 'NOT_SUBMITTED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: null,
      },
    ],
  },
  {
    id: 'ec-002',
    class_name: 'Grade 12 Physics',
    class_year: '2026',
    teacher_name: 'Mr. Rohan Fernando',
    subject: 'Physics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'PENDING',
    enrolled_at: '2026-01-20T09:00:00.000Z',
    monthly_fee: 2800,
    description: 'Advanced Physics covering mechanics, electromagnetism, waves, and modern physics with practical sessions.',
    papers: [
      {
        id: 'paper-002-1',
        paper_name: 'Monthly Paper 01 – June 2026',
        due_date: '2026-06-18T23:59:00.000Z',
        submission_status: 'SUBMITTED',
      },
    ],
    previous_papers: [
      {
        id: 'prev-002-1',
        paper_name: 'Monthly Paper 01 – May 2026',
        due_date: '2026-05-18T23:59:00.000Z',
        grade: '91/100',
        status: 'GRADED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: 'https://placehold.co/600x800?text=My+Submission',
        graded_pdf_url: 'https://placehold.co/600x800?text=Graded+Submission',
      },
      {
        id: 'prev-002-2',
        paper_name: 'Monthly Paper 02 – May 2026',
        due_date: '2026-05-25T23:59:00.000Z',
        grade: null,
        status: 'NOT_SUBMITTED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: null,
      },
      {
        id: 'prev-002-3',
        paper_name: 'Monthly Paper 01 – April 2026',
        due_date: '2026-04-18T23:59:00.000Z',
        grade: '79/100',
        status: 'GRADED',
        exam_pdf_url: 'https://placehold.co/600x800?text=Exam+Paper+PDF',
        submission_url: 'https://placehold.co/600x800?text=My+Submission',
        graded_pdf_url: 'https://placehold.co/600x800?text=Graded+Submission',
      },
    ],
  },
  {
    id: 'ec-003',
    class_name: 'Grade 12 Combined Mathematics',
    class_year: '2026',
    teacher_name: 'Ms. Tharindi Wickrama',
    subject: 'Combined Mathematics',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'NOT_PAID',
    enrolled_at: '2026-02-01T10:00:00.000Z',
    monthly_fee: 3000,
    description: 'Pure and Applied Mathematics combined course for Physical Science stream students.',
    papers: [],
    previous_papers: [],
  },
  {
    id: 'ec-004',
    class_name: 'Grade 12 Chemistry',
    class_year: '2026',
    teacher_name: 'Mr. Kasun Silva',
    subject: 'Chemistry',
    image_url: 'https://placehold.co/400x200?text=Class+Image',
    payment_status: 'REJECTED',
    enrolled_at: '2026-02-05T11:00:00.000Z',
    monthly_fee: 2600,
    description: 'Comprehensive Chemistry course covering organic, inorganic, and physical chemistry with lab practicals.',
    papers: [],
    previous_papers: [],
  },
];

export const MOCK_PAYMENTS = [
  // ── PENDING (4) ────────────────────────────────────────────────────────────
  {
    id: 'pay-001',
    student_id: '1',
    student_name: 'Amal Perera',
    student_number: 'SUBMITX-2026-000001',
    teacher_name: 'Mr. Kasun Silva',
    class_name: 'Grade 10 Biology Fundamentals',
    amount: 2000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-09T08:15:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-002',
    student_id: '2',
    student_name: 'Sanduni Wickramasinghe',
    student_number: 'SUBMITX-2026-000002',
    teacher_name: 'Ms. Nimasha Jayawardena',
    class_name: 'Grade 9 English Literature',
    amount: 1800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-09T11:30:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-003',
    student_id: '3',
    student_name: 'Kasun Jayawardena',
    student_number: 'SUBMITX-2026-000003',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-08T14:45:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  {
    id: 'pay-004',
    student_id: '4',
    student_name: 'Dilini Bandara',
    student_number: 'SUBMITX-2026-000004',
    teacher_name: 'Ms. Tharindi Wickrama',
    class_name: 'Grade 11 Chemistry Lab',
    amount: 3000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'PENDING',
    reference_number: null,
    rejection_reason: null,
    submitted_at: '2026-06-08T09:00:00.000Z',
    reviewed_at: null,
    reviewed_by: null,
  },
  // ── APPROVED (3) ───────────────────────────────────────────────────────────
  {
    id: 'pay-005',
    student_id: '5',
    student_name: 'Tharaka Silva',
    student_number: 'SUBMITX-2026-000005',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'BOC-2026-TXN-00441',
    rejection_reason: null,
    submitted_at: '2026-06-07T10:00:00.000Z',
    reviewed_at: '2026-06-07T15:30:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  {
    id: 'pay-006',
    student_id: '1',
    student_name: 'Amal Perera',
    student_number: 'SUBMITX-2026-000001',
    teacher_name: 'Ms. Nimasha Jayawardena',
    class_name: 'Grade 9 English Literature',
    amount: 1800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'HNB-2026-RTF-08812',
    rejection_reason: null,
    submitted_at: '2026-06-06T13:00:00.000Z',
    reviewed_at: '2026-06-06T16:45:00.000Z',
    reviewed_by: 'Dinesh Bandara',
  },
  {
    id: 'pay-007',
    student_id: '2',
    student_name: 'Sanduni Wickramasinghe',
    student_number: 'SUBMITX-2026-000002',
    teacher_name: 'Mr. Kasun Silva',
    class_name: 'Grade 10 Biology Fundamentals',
    amount: 2000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'APPROVED',
    reference_number: 'COMM-2026-CRD-55019',
    rejection_reason: null,
    submitted_at: '2026-06-05T09:30:00.000Z',
    reviewed_at: '2026-06-05T11:15:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  // ── REJECTED (3) ───────────────────────────────────────────────────────────
  {
    id: 'pay-008',
    student_id: '3',
    student_name: 'Kasun Jayawardena',
    student_number: 'SUBMITX-2026-000003',
    teacher_name: 'Ms. Tharindi Wickrama',
    class_name: 'Grade 11 Chemistry Lab',
    amount: 3000,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'Receipt image is blurry and unreadable. Please upload a clear photograph of the bank deposit slip.',
    submitted_at: '2026-06-07T08:00:00.000Z',
    reviewed_at: '2026-06-07T09:30:00.000Z',
    reviewed_by: 'Dinesh Bandara',
  },
  {
    id: 'pay-009',
    student_id: '4',
    student_name: 'Dilini Bandara',
    student_number: 'SUBMITX-2026-000004',
    teacher_name: 'Dr. Anusha Perera',
    class_name: 'Grade 12 Advanced Mathematics',
    amount: 2500,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'The deposited amount (LKR 2,000) does not match the required fee (LKR 2,500). Please deposit the correct amount and resubmit.',
    submitted_at: '2026-06-06T07:45:00.000Z',
    reviewed_at: '2026-06-06T10:00:00.000Z',
    reviewed_by: 'Priya Rathnayake',
  },
  {
    id: 'pay-010',
    student_id: '5',
    student_name: 'Tharaka Silva',
    student_number: 'SUBMITX-2026-000005',
    teacher_name: 'Mr. Rohan Fernando',
    class_name: 'Grade 13 Physics',
    amount: 2800,
    receipt_url: 'https://placehold.co/600x400?text=Payment+Slip',
    status: 'REJECTED',
    reference_number: null,
    rejection_reason: 'Duplicate submission — this payment has already been processed under reference BOC-2026-TXN-00441.',
    submitted_at: '2026-06-05T14:00:00.000Z',
    reviewed_at: '2026-06-05T16:30:00.000Z',
    reviewed_by: 'Sanduni Madushanka',
  },
];

export const MOCK_LOGGED_IN_TEACHER = {
  id: '1',
  first_name: 'Anusha',
  last_name: 'Perera',
  email: 'anusha.perera@submitx.app',
  contact_number: '+94771234567',
  subject_area: 'Mathematics',
  bio: 'Advanced mathematics teacher focused on A/L problem solving and structured revision.',
  profile_image_url: null,
  username: 'anusha.perera',
  status: 'ACTIVE',
  created_at: '2026-01-10T08:30:00.000Z',
};

export const MOCK_CASHIERS = [
  {
    id: '1',
    fullName: 'Priya Rathnayake',
    email: 'priya.r@submitx.app',
    username: 'priya_r',
    password: 'Cash!2024X',
  },
  {
    id: '2',
    fullName: 'Dinesh Bandara',
    email: 'dinesh.b@submitx.app',
    username: 'dinesh_b',
    password: 'Desk@99A!',
  },
  {
    id: '3',
    fullName: 'Sanduni Madushanka',
    email: 'sanduni.m@submitx.app',
    username: 'sanduni_m',
    password: 'Sand!Pay8Z',
  },
];
